name: Action Test

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repo"
        type: string
        required: true
      milestone:
        description: "Milestone"
        type: string
        required: true

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:  
  test:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - name: Get release notes
        uses: Beakyn/gha-format-release-notes@v1
        id: get-release-notes
        with:
          repository: ${{ github.event.inputs.repository }}
          milestone: ${{ github.event.inputs.milestone }}
      - name: Print release notes
        run: |
          echo "${{ steps.get-release-notes.outputs.release-notes }}"
