name: Test workflow 1

on:
  workflow_dispatch:

jobs:
  prod-check:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Production branch ref
        run:
          echo "Cannot deploy to production server from a branch different of 'main'"
          exit 1
        # run: echo "Deploying to production server on branch $GITHUB_REF"
  test-workflow:
    needs: [prod-check]
    uses: felipe-rastelli/github-workflow-test-repo/.github/workflows/branch-test-workflow-2.yml@develop
  test-steps1:
    needs: [test-workflow]
    runs-on: ubuntu-latest
    steps:
      - name: Echo after test
        run: echo 'This is a test'
      - name: Print event context
        env:
          EVENT_CONTEXT: ${{ toJson(github.event) }}
        run: echo $EVENT_CONTEXT
  # post-prod-check:
  #   if: ${{ github.ref != 'refs/heads/main' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Post Check Production branch ref
  #       run: echo "Cannot deploy to production server from a branch different of 'master'"
