name: Build

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version to setup environment"
        required: true
        type: string
      node-cache:
        description: "Package manager to cache dependencies"
        required: true
        type: string

jobs:
  build:
    name: Production
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: 'echo "Running application build."'
