name: Check Graphql Schema

on:
  workflow_call

jobs:
  validate-schema:
    name: Validate schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v2

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: main:src/schema.graphql
          approve-label: approved-schema-breaking-change
          experimental_merge: false
