on:
  pull_request:
    branches:
      - develop
    # paths-ignore:
    #   - '.github/**'

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ toJSON(github) }}'

  call-lint:
    name: Lint Code
    uses: felipe-rastelli/github-workflow-test-repo/.github/workflows/lint.yml@test2
    with:
      node-version: 16.13
      node-cache: yarn
  call-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        run: echo "Building the application…"
  call-test:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Test application
        run: echo "Testing the application…"

