name: Code Quality Check

on:
  pull_request:
    branches:
      - develop
    # paths-ignore:
    #   - '.github/**'

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-lint:
    uses: felipe-rastelli/github-workflow-test-repo/.github/workflows/lint.yml@test2
    with:
      node-version: 16.13
      node-cache: yarn
  call-build:
    runs-on: ubuntu-latest
    needs: call-lint
    steps:
      - name: Build application
        run: echo "Building the application…"
  call-test:
    runs-on: ubuntu-latest
    needs: call-build
    steps:
      - name: Test application
        run: echo "Testing the application…"

