name: Create Release

on:
  workflow_dispatch:
    inputs:
      milestone-id:
        description: Milestone ID to get release info
        type: string
        required: true

concurrency:
  cancel-in-progress: true
  group: cd-${{ github.workflow }}-${{ github.ref }}
  
jobs:
  release-prod:
    name: Create Release Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Get next version tag
        id: get-next-version-tag
        run: |
          milestone="$(gh api repos/$GITHUB_REPOSITORY/milestones/$MILESTONE_ID --jq '.title')"
          echo "::echo::on"
          echo "::set-output name=next-version::$milestone"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          MILESTONE_ID: ${{ github.event.inputs.milestone-id }}

      - name: Get release notes
        uses: Beakyn/gha-format-release-notes@v1
        id: get-release-notes
        with:
          repository: ${{ github.repository }}
          milestone: ${{ github.event.inputs.milestone-id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout to repository
        uses: actions/checkout@v3

      - name: Config git user
        run: |
          git config user.name ${{ github.actor }}

      - name: Checkout to release branch
        run: |
          git checkout -b release/${{ steps.get-next-version-tag.outputs.next-version }}
        
      - name: Bump version
        run: |
          npm --no-git-tag-version version ${{ steps.get-next-version-tag.outputs.next-version }}

      - name: Write changelog
        id: write-changelog
        run: |
          today=$(date +%F)
          body="## ${{ steps.get-next-version-tag.outputs.next-version }} ($today) \n\n${{ steps.get-release-notes.outputs.release-notes }}\n"

          { head -n 4 CHANGELOG.md; printf "$body"; tail -n +5 CHANGELOG.md; } > temp && mv temp CHANGELOG.md
          cat CHANGELOG.md

          echo "::echo::on"
          echo "::set-output name=changelog::$body"          

      - name: Commit changes
        run: |
          git add .
          git commit -m "Release ${{ steps.get-next-version-tag.outputs.next-version }}"

      - name: Create release PR
        run: |
          body="## Releasing version $VERSION \n\n${{ steps.write-changelog.outputs.changelog }}"

          gh pr create --milestone $MILESTONE_ID \
            --title "Release $VERSION" \
            --body $body \
            --base $BASE_BRANCH \
            --assignee $ASSIGNEE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MILESTONE_ID: ${{ github.event.inputs.milestone-id }}
          BASE_BRANCH: master
          ASSIGNEE: ${{ github.actor }}
          VERSION: ${{ steps.get-next-version-tag.outputs.next-version }}
