name: Lint

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'ignored/**'

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No lint required."'