name: PR Code Check

on:
  pull_request:
    branches:
      - develop
    # paths-ignore:
    #   - '.github/**'

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-lint:
    name: Call Lint
    uses: felipe-rastelli/github-workflow-test-repo/.github/workflows/lint.yml@develop
    with:
      node-version: 16.13
      node-cache: yarn
  call-build:
    needs: call-lint
    name: Call Build
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Building the application…"'
  call-test:
    needs: call-lint
    name: Call Test
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Testing the application…"'
  call-deploy-preview:
    name: Call Deploy
    needs: [call-build, call-test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (Preview)
        run: echo "Deploying the application…"

