name: PR Code Check

on:
  pull_request:
    branches:
      - develop
    # paths-ignore:
    #   - '.github/**'

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-lint:
    uses: felipe-rastelli/github-workflow-test-repo/.github/workflows/lint.yml@lint-workflow-test
    with:
      node-version: 16.13
      node-cache: yarn
  call-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Building the application…"'
  call-test:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Testing the application…"'
  call-deploy-preview:
    name: Deploy/Preview
    needs: [call-build, call-test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (Preview)
        run: echo "Deploying the application…"

