name: PR Code Check

on:
  pull_request:
    branches:
      - develop
    # paths-ignore:
    #   - '.github/**'

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # call-lint:
  #   name: Lint
  #   uses: felipe-rastelli/github-workflow-test-repo/.github/workflows/lint.yml@develop
  #   with:
  #     node-version: 16.13
  #     node-cache: yarn
  call-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        run: echo "Building the application…"
  call-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test application
        run: echo "Testing the application…"

