name: Test Workflow

on:
  workflow_dispatch:  

concurrency:
  group: cd-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  workflow-1:
    name: Workflow 1
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
      - name: Step 1
        run: echo "Workflow 1 - Step 1"
      - name: Step 2
        run: exit 1

  workflow-2:
    name: Workflow 2
    runs-on: ubuntu-latest
    needs: workflow-1
    if: ${{ needs.workflow-1.result == 'success' || needs.workflow-1.result == 'skipped' }}
    steps:
      - name: Step 1
        run: echo "Workflow 2 - Step 1"
